# Generated by Django 5.2.11 on 2026-02-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "price_start",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço inicial (A partir de)",
                        max_digits=10,
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Nome do ícone (ex: format-paint)", max_length=50
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("rating", models.IntegerField(default=5, help_text="Nota de 1 a 5")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
