# Generated by Django 5.2.11 on 2026-02-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('combo', 'Combo (Sequência)'), ('individual', 'Tratamento Individual')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='Ex: 4 dias, 4 horas', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='installment_max',
            field=models.IntegerField(default=1, help_text='Número máximo de parcelas'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_cash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço à vista (com desconto)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='warranty_time',
            field=models.CharField(blank=True, help_text='Ex: 9 meses, 3 anos', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Nome do ícone ou Emoji', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
